[workspace]
members = [
    "auth",
    "bootstrap",
    "certs",
    "channels",
    "clients",
    "domains",
    "examples",
    "groups",
    "http",
    "invitations",
    "journal",
    "notifiers",
    "provision",
    "readers",
    "twins",
    "users"

]

