/*
 * Magistrala Domains Service
 *
 * This is the Domains Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform domains. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableActionsObj {
    /// List of all available actions.
    #[serde(rename = "available_actions", skip_serializing_if = "Option::is_none")]
    pub available_actions: Option<Vec<String>>,
}

impl AvailableActionsObj {
    pub fn new() -> AvailableActionsObj {
        AvailableActionsObj {
            available_actions: None,
        }
    }
}

