/*
 * SuperMQ Bootstrap service
 *
 * HTTP API for managing platform clients configuration. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigUpdateCerts {
    /// Corresponding SuperMQ Client ID.
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    /// Client certificate.
    #[serde(rename = "client_cert", skip_serializing_if = "Option::is_none")]
    pub client_cert: Option<String>,
    /// Key for the client_cert.
    #[serde(rename = "client_key")]
    pub client_key: String,
    /// Issuing CA certificate.
    #[serde(rename = "ca_cert", skip_serializing_if = "Option::is_none")]
    pub ca_cert: Option<String>,
}

impl ConfigUpdateCerts {
    pub fn new(client_id: uuid::Uuid, client_key: String) -> ConfigUpdateCerts {
        ConfigUpdateCerts {
            client_id,
            client_cert: None,
            client_key,
            ca_cert: None,
        }
    }
}

