/*
 * SuperMQ Bootstrap service
 *
 * HTTP API for managing platform clients configuration. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConfigRequest {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateConfigRequest {
    pub fn new(content: String, name: String) -> UpdateConfigRequest {
        UpdateConfigRequest {
            content,
            name,
        }
    }
}

