/*
 * SuperMQ Bootstrap service
 *
 * HTTP API for managing platform clients configuration. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConfigStateRequest {
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::State>,
}

impl UpdateConfigStateRequest {
    pub fn new() -> UpdateConfigStateRequest {
        UpdateConfigStateRequest {
            state: None,
        }
    }
}

