/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateRoleObj {
    /// Role's name.
    #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
    /// List of optional actions.
    #[serde(rename = "optional_actions", skip_serializing_if = "Option::is_none")]
    pub optional_actions: Option<Vec<String>>,
    /// List of optional members.
    #[serde(rename = "optional_members", skip_serializing_if = "Option::is_none")]
    pub optional_members: Option<Vec<String>>,
}

impl CreateRoleObj {
    pub fn new() -> CreateRoleObj {
        CreateRoleObj {
            role_name: None,
            optional_actions: None,
            optional_members: None,
        }
    }
}


