/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupUpdate {
    /// Free-form group name. Group name is unique on the given hierarchy level.
    #[serde(rename = "name")]
    pub name: String,
    /// Group description, free form text.
    #[serde(rename = "description")]
    pub description: String,
    /// Arbitrary, object-encoded groups's data.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl GroupUpdate {
    pub fn new(name: String, description: String, metadata: serde_json::Value) -> GroupUpdate {
        GroupUpdate {
            name,
            description,
            metadata,
        }
    }
}


